name: Sonar Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v2
        with:
          path: .
    
      - name: Print working directory
        run: pwd

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'

      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
            echo "/apps/dftjenkins/.local/bin" >> $GITHUB_PATH
      - name: Run tests with coverage
        run: |
            coverage run --source=src -m unittest discover tests
            coverage xml -o coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}